//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_12_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classification
    {
        public Classification()
        {
            this.Speciality = new HashSet<Speciality>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Speciality> Speciality { get; set; }
    }
}
