//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_12_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        public Curriculum()
        {
            this.CurriculumDiscipline = new HashSet<CurriculumDiscipline>();
        }
    
        public long Id { get; set; }
        public long SpecialityId { get; set; }
    
        public virtual Speciality Speciality { get; set; }
        public virtual ICollection<CurriculumDiscipline> CurriculumDiscipline { get; set; }
    }
}
