//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_12_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurriculumDiscipline
    {
        public long Id { get; set; }
        public long CurriculumId { get; set; }
        public long DisciplineId { get; set; }
        public int HoursForDiscipline { get; set; }
        public short Term { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        public virtual Discipline Discipline { get; set; }
    }
}
