//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_12_FirstTry.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ViPKS_PR12Entities : DbContext
    {
        public ViPKS_PR12Entities()
            : base("name=ViPKS_PR12Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Classification> Classification { get; set; }
        public DbSet<Classroom> Classroom { get; set; }
        public DbSet<Curriculum> Curriculum { get; set; }
        public DbSet<CurriculumDiscipline> CurriculumDiscipline { get; set; }
        public DbSet<Discipline> Discipline { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<Grade> Grade { get; set; }
        public DbSet<LibraryItem> LibraryItem { get; set; }
        public DbSet<LibraryLoan> LibraryLoan { get; set; }
        public DbSet<Schedule> Schedule { get; set; }
        public DbSet<Speciality> Speciality { get; set; }
        public DbSet<Student> Student { get; set; }
        public DbSet<StudyGroup> StudyGroup { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Teacher> Teacher { get; set; }
    }
}
