//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_12_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Grade = new HashSet<Grade>();
        }
    
        public long Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public long StudyGroupId { get; set; }
        public long TeacherId { get; set; }
        public long DisciplineId { get; set; }
        public long ClassroomId { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Discipline Discipline { get; set; }
        public virtual ICollection<Grade> Grade { get; set; }
        public virtual StudyGroup StudyGroup { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
