//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_12_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speciality
    {
        public Speciality()
        {
            this.Curriculum = new HashSet<Curriculum>();
            this.StudyGroup = new HashSet<StudyGroup>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string TermOfEducation { get; set; }
        public long ClassificationId { get; set; }
    
        public virtual Classification Classification { get; set; }
        public virtual ICollection<Curriculum> Curriculum { get; set; }
        public virtual ICollection<StudyGroup> StudyGroup { get; set; }
    }
}
