//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_12_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyGroup
    {
        public StudyGroup()
        {
            this.Schedule = new HashSet<Schedule>();
            this.Student = new HashSet<Student>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public long SpecialityId { get; set; }
    
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual Speciality Speciality { get; set; }
        public virtual ICollection<Student> Student { get; set; }
    }
}
