//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_12_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Grade = new HashSet<Grade>();
            this.LibraryLoan = new HashSet<LibraryLoan>();
        }
    
        public long Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public long StudyGroupId { get; set; }
        public string Passport { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<long> TypeOfEducationId { get; set; }
    
        public virtual ICollection<Grade> Grade { get; set; }
        public virtual ICollection<LibraryLoan> LibraryLoan { get; set; }
        public virtual StudyGroup StudyGroup { get; set; }
        public virtual TypeOfEducation TypeOfEducation { get; set; }
    }
}
